### PR TITLE
fix: add a way to override userdata

### PR DESCRIPTION
**Pull request by ntwkninja**
This enables adding custom user_data when the default user_data is not used

### CODE REVIEW

**Review by brianrexrode — DISMISSED** [review]
lgtm

**Review by JaseKoonce — CHANGES_REQUESTED** [review]
With the current configuration, the vars passed into userdata will still be required. Additional logic will be needed so TF either doesn't try to create `cloudinit_config.config`  or  at least doesnt throw errors when an input to `user_data_override` is passed.

**Review by JaseKoonce — DISMISSED** [review]
LGTM

**Review by JaseKoonce — APPROVED** [review]

**Pull request merged**
